/*
 * DC_MOTOR.c
 *
 * Created: 31/12/2021 03:42:09 م
 *  Author: dell
 */ 
#include "DC_MOTOR_CFG.h"
#include "DC_MOTOR.h"
#include "DIO.h"
#include "TIMERS.h"

void DC_MOTORS_INIT(void)
{
	//RIGHT MOTOR STARTS
	PIN_MODE(RIGHT_DC_MOTOR_DIRECTION_1,OUTPUT);
	PIN_MODE(RIGHT_DC_MOTOR_DIRECTION_2,OUTPUT);
	PIN_MODE(RIGHT_DC_MOTOR_ENABLE_1 ,OUTPUT);
	
	//LEFT MOTOR STARTS
	PIN_MODE(LEFT_DC_MOTOR_DIRECTION_1,OUTPUT);
	PIN_MODE(LEFT_DC_MOTOR_DIRECTION_2 ,OUTPUT);
	PIN_MODE(LEFT_DC_MOTOR_ENABLE_2 ,OUTPUT);
}

void DC_MOTORS_START(u8 direction)
{
	PIN_WRITE(RIGHT_DC_MOTOR_ENABLE_1 ,HIGH);
	PIN_WRITE(LEFT_DC_MOTOR_ENABLE_2 ,HIGH);
	
	switch(direction)
	{
		case FORWARD:
		PIN_WRITE(RIGHT_DC_MOTOR_DIRECTION_1,HIGH);
		PIN_WRITE(RIGHT_DC_MOTOR_DIRECTION_2,LOW);
		PIN_WRITE(LEFT_DC_MOTOR_DIRECTION_1,HIGH);
		PIN_WRITE(LEFT_DC_MOTOR_DIRECTION_2 ,LOW);
		break;
		
		case BACKWARD:
		PIN_WRITE(RIGHT_DC_MOTOR_DIRECTION_1,LOW);
		PIN_WRITE(RIGHT_DC_MOTOR_DIRECTION_2,HIGH);
		PIN_WRITE(LEFT_DC_MOTOR_DIRECTION_1,LOW);
		PIN_WRITE(LEFT_DC_MOTOR_DIRECTION_2 ,HIGH);
		break;
		
		case RIGHT:
		PIN_WRITE(RIGHT_DC_MOTOR_DIRECTION_1,LOW);
		PIN_WRITE(RIGHT_DC_MOTOR_DIRECTION_2,LOW);
		PIN_WRITE(LEFT_DC_MOTOR_DIRECTION_1,HIGH);
		PIN_WRITE(LEFT_DC_MOTOR_DIRECTION_2 ,LOW);
		break;
		
		case LEFT:
		PIN_WRITE(LEFT_DC_MOTOR_DIRECTION_1,LOW);
		PIN_WRITE(LEFT_DC_MOTOR_DIRECTION_2 ,LOW);
		PIN_WRITE(RIGHT_DC_MOTOR_DIRECTION_1,HIGH);
		PIN_WRITE(RIGHT_DC_MOTOR_DIRECTION_2,LOW);
		break;
		
		default:
		break;
	}
}

void DC_MOTORS_STOP(void)
{
	PIN_WRITE(RIGHT_DC_MOTOR_DIRECTION_1,LOW);
	PIN_WRITE(RIGHT_DC_MOTOR_DIRECTION_2,LOW);
	PIN_WRITE(LEFT_DC_MOTOR_DIRECTION_1,LOW);
	PIN_WRITE(LEFT_DC_MOTOR_DIRECTION_2 ,LOW);
	PIN_WRITE(RIGHT_DC_MOTOR_ENABLE_1 ,LOW);
	PIN_WRITE(LEFT_DC_MOTOR_ENABLE_2 ,LOW);
}
