/*
 * STEPPER.c
 *
 * Created: 17/12/2021 02:14:04 م
 *  Author: dell
 */ 
#include "STEPPER_CFG.h"
#include "STD.h"
#include "DIO.h"
#define F_CPU 16000000
#include <util/delay.h>

void STEPPER_INIT(void)
{
	PIN_MODE(STEPPER_MOTOR_PIN_1,OUTPUT);
	PIN_MODE(STEPPER_MOTOR_PIN_2,OUTPUT);
	PIN_MODE(STEPPER_MOTOR_PIN_3,OUTPUT);
	PIN_MODE(STEPPER_MOTOR_PIN_4,OUTPUT);
}
void STEPPER_ON(u8 x)
{
	u8 j = 0;
	for(j=0;j<x;j++)
	{
		PIN_WRITE(STEPPER_MOTOR_PIN_1,HIGH);
	    PIN_WRITE(STEPPER_MOTOR_PIN_2,LOW);
	    PIN_WRITE(STEPPER_MOTOR_PIN_3,LOW);
	    PIN_WRITE(STEPPER_MOTOR_PIN_4,LOW);
	    _delay_ms(5);
	    PIN_WRITE(STEPPER_MOTOR_PIN_1,LOW);
	    PIN_WRITE(STEPPER_MOTOR_PIN_2,HIGH);
	    PIN_WRITE(STEPPER_MOTOR_PIN_3,LOW);
	    PIN_WRITE(STEPPER_MOTOR_PIN_4,LOW);
	    _delay_ms(5);
	    PIN_WRITE(STEPPER_MOTOR_PIN_1,LOW);
	    PIN_WRITE(STEPPER_MOTOR_PIN_2,LOW);
	    PIN_WRITE(STEPPER_MOTOR_PIN_3,HIGH);
	    PIN_WRITE(STEPPER_MOTOR_PIN_4,LOW);	
	    _delay_ms(5);
	    PIN_WRITE(STEPPER_MOTOR_PIN_1,LOW);
	    PIN_WRITE(STEPPER_MOTOR_PIN_2,LOW);
	    PIN_WRITE(STEPPER_MOTOR_PIN_3,LOW);
	    PIN_WRITE(STEPPER_MOTOR_PIN_4,HIGH);
		_delay_ms(5);
	}
}